### ISSUE TITLE
Currencies Updating

### ISSUE THREAD

**Issue by LikeyX** [MrWaip/PoE-Trade-Bot-C-#3]
Class Currencies.cs: Line 60
> https://poe.ninja/api/data/currencyoverview?league=Metamorph&type=Currency&language=en 
> For Metamorph
> 
> https://poe.ninja/api/data/currencyoverview?league=Hardcore%20Metamorph&type=Currency&language=en
> For Metamorph HC
> 
> https://poe.ninja/api/data/currencyoverview?league=Standard&type=Currency&language=en
> For Standard
> 
> https://poe.ninja/api/data/currencyoverview?league=Hardcore&type=Currency&language=en
> For Standard HC

Class Currencies.cs: Line 63
Newtonsoft.Json.JsonReaderException: "Unexpected character encountered while parsing Value: <. Path ", line 0, position 0. 

I think it has something to do with the link i mentioned above? 

---- Updated Link Runs into error "Can't convert type Null into Double
![null](https://user-images.githubusercontent.com/27165564/72749478-728cb000-3bba-11ea-9fc6-0b6d8dfc8e74.PNG)

**Comment by X00149488** [comment]
same thing happened to me !

**Comment by X00149488** [comment]
I changed line to obtain data For metamorph and its throws this:

System.Runtime.InteropServices.ExternalException
  HResult=0x80004005
  Message=A generic error occurred in GDI+.
  Source=System.Drawing
  StackTrace:
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.Save(String filename, ImageFormat format)
   at Emgu.CV.Mat.Save(String fileName)
   at Emgu.CV.Image`2.Save(String fileName)
   at PoE_Trade_Bot.Services.OpenCV_Service.FindObject(Bitmap source_img, String path_template) in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\Services\OpenCV_Service.cs:line 87
   at PoE_Trade_Bot.BotEngine.OpenStash() in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\BotEngine.cs:line 538
   at PoE_Trade_Bot.BotEngine.StartTrader_PoEbota() in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\BotEngine.cs:line 318
   at PoE_Trade_Bot.BotEngine.StartBot() in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\BotEngine.cs:line 69
   at PoE_Trade_Bot.Program.Main(String[] args) in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\Program.cs:line 21

**Comment by LikeyX** [comment]
I had to make some properties Nullable to reach this point (Standard league)

> I changed line to obtain data For metamorph and its throws this:
> 
> System.Runtime.InteropServices.ExternalException
> HResult=0x80004005
> Message=A generic error occurred in GDI+.
> Source=System.Drawing
> StackTrace:
> at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
> at System.Drawing.Image.Save(String filename, ImageFormat format)
> at Emgu.CV.Mat.Save(String fileName)
> at Emgu.CV.Image`2.Save(String fileName)
> at PoE_Trade_Bot.Services.OpenCV_Service.FindObject(Bitmap source_img, String path_template) in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\Services\OpenCV_Service.cs:line 87
> at PoE_Trade_Bot.BotEngine.OpenStash() in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\BotEngine.cs:line 538
> at PoE_Trade_Bot.BotEngine.StartTrader_PoEbota() in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\BotEngine.cs:line 318
> at PoE_Trade_Bot.BotEngine.StartBot() in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\BotEngine.cs:line 69
> at PoE_Trade_Bot.Program.Main(String[] args) in C:\Users\Jack\Desktop\PoE-Trade-Bot-C--master\PoE-Trade-Bot-C--master\Program.cs:line 21

Class OpenCV_Service Line 87 need to be changed into "result.Save(@"C:\Users\Jack\Desktop" + DateTime.Now.ToShortDateString() + ".png");"
for example. But i'm to tired now to analyze this further ;) 

Can you choose the suggested Resolution? 

Actually i'm to tired to analyze it further.

**Comment by X00149488** [comment]
Yes i did change it  and yes resolution is 1366x768, throws same thing

**Comment by LikeyX** [comment]
> Yes i did change it and yes resolution is 1366x768, throws same thing
> 
> something wrong in that line 87 class OpenCV_Service

Yes, as i told you, you have to change the line to your path. 

I tested around alot, could fix some things (for my pc) but there are many many problems ongoing. For example it does not find the stash with the "Open_stash.png". If i add my own "Open_stash2.png" it find the stash, but runs into pixel error (ROI). I think in this state, the program is only runnable on his notebook, cause its to static programmed. I might be wrong, because i'm not a programmer, but that's my current point of view.

**Comment by BapnB** [comment]
![image](https://user-images.githubusercontent.com/25757064/72761927-a255ab00-3bee-11ea-9fe7-0676b2b87a52.png)
what is this?

**Comment by LikeyX** [comment]
> ![image](https://user-images.githubusercontent.com/25757064/72761927-a255ab00-3bee-11ea-9fe7-0676b2b87a52.png)
> what is this?

I think the middle of a Inventory Cell in Pixel he adds.

![image](https://user-images.githubusercontent.com/27165564/72774159-d7232b80-3c09-11ea-8ae5-e7d0491dcb29.png)

**Comment by olaims** [comment]
> 
> 
> Class Currencies.cs: Line 60
> 
> > https://poe.ninja/api/data/currencyoverview?league=Metamorph&type=Currency&language=en
> > For Metamorph
> > https://poe.ninja/api/data/currencyoverview?league=Hardcore%20Metamorph&type=Currency&language=en
> > For Metamorph HC
> > https://poe.ninja/api/data/currencyoverview?league=Standard&type=Currency&language=en
> > For Standard
> > https://poe.ninja/api/data/currencyoverview?league=Hardcore&type=Currency&language=en
> > For Standard HC
> 
> Class Currencies.cs: Line 63
> Newtonsoft.Json.JsonReaderException: "Unexpected character encountered while parsing Value: <. Path ", line 0, position 0.
> 
> I think it has something to do with the link i mentioned above?
> 
> ---- Updated Link Runs into error "Can't convert type Null into Double
> ![null](https://user-images.githubusercontent.com/27165564/72749478-728cb000-3bba-11ea-9fc6-0b6d8dfc8e74.PNG)

For ritual the URL should be updated to something like:

https://poe.ninja/api/data/currencyoverview?league=Ritual&type=Currency

inside Currencies.cs line 61
