### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by LikeyX** [MrWaip/PoE-Trade-Bot-C-#4]
The fix resolution you took isn't choosable on all devices. 

Class OpenCV_Service.cs
Line 87: result.Save(@"....) <-- Should be variable and not fix on your User ;-)

![image](https://user-images.githubusercontent.com/27165564/72750549-7a018880-3bbd-11ea-8e6c-54b969529a68.png)

**Comment by X00149488** [comment]
I think you have to choose just "windowed" and then you will able to change it

**Comment by LikeyX** [comment]
> I think you have to choose just "windowed" and then you will able to change it

The only way i can setup the needed Resolution is to make it windowed and resize it manually at the corners ;)

**Comment by botallu1701** [comment]
any1 fix that error on line 87 at Opencv_service.cs?

**Comment by LikeyX** [comment]
> any1 fix that error on line 87 at Opencv_service.cs?

You have to change  the line from 

result.Save(@"C:\Users\Jack\..." + DateTime.Now.ToShortDateString() + ".png");

to your User path (From Jack to botallu1701 for example)

**Comment by barisbulutdemir** [comment]
did you fix it ? @LikeyX  i m trying runing bot but i can't :/

**Comment by LikeyX** [comment]
> did you fix it ? @LikeyX i m trying runing bot but i can't :/

Got no time to reproduce every error atm. It may be easier to try to contact the Programmer.

**Comment by barisbulutdemir** [comment]
@LikeyX  i try contact the programmer but not answer. i m writing on facebook. Do you have his mail ?

**Comment by MrWaip** [comment]
Sorry. It's my pet project. It have to be reworked.
