### ISSUE TITLE
HOW IS IT USED

### ISSUE THREAD

**Issue by instak1ll** [MrWaip/PoE-Trade-Bot-C-#7]
SOMEONE CAN EXPLAIN HOW I CAN EXECUTE IT AND MAKE IT DO THE AUTOMATIC TRADES, SOME VIDEOS FOR NOBS

**Comment by instak1ll** [comment]
PLS

**Comment by MovieZo** [comment]
> PLS

Sorry, there is no way that you can make it runnable if you are not a programmer. There are many bugs etc, been playing with it whole day and still many things left to do..

**Comment by MrWaip** [comment]
I don't remember how it work, how it start. It was long time ago XD
