### ISSUE TITLE
Local Folder Associations

### ISSUE THREAD

**Issue by Kritikally-Akklaimed** [MrWaip/PoE-Trade-Bot-C-#8]
In "OpenCV_Service.cs" and "ScreenCapture.cs", you are referring to a local file location that needs to be changed to the result of an environment variable.

Pull environment variable for %USERPROFILE%, then replace "C:\Users\MrWaip" with the result of %USERPROFILE%.

**Comment by Kritikally-Akklaimed** [comment]
In "Program.cs", you are also referring to a local file location that may need to be changed.
It is referring to a drive/folder named "D:\Test" that will fail if the drive and folder do not exist on the machine.  I would suggest also changing this entry to some folder based on the %USERPROFILE% to prevent errors on launch.

**Comment by MrWaip** [comment]
You are right. It have to be in config.

**Comment by MrWaip** [comment]
I'm just trying to remember what the hell I wrote two years ago =)
